# Generated by Django 2.2 on 2019-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_choices', models.CharField(choices=[('J', 'Jan Extended'), ('F', 'Feb Standard'), ('A', 'Aug Standard'), ('M', 'May Express'), ('O', 'October Express')], max_length=1)),
                ('sl_xls', models.FileField(upload_to='student_list/%Y-%m-%d/%H/%M')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
