# Generated by Django 2.2 on 2019-04-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='year_choices',
            field=models.CharField(choices=[('18', '2018'), ('19', '2019'), ('20', '2020'), ('21', '2021')], default='18', max_length=2),
            preserve_default=False,
        ),
    ]
