# Generated by Django 2.2 on 2019-04-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentlist_year_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_choices', models.CharField(choices=[('18', '2018'), ('19', '2019'), ('20', '2020'), ('21', '2021')], max_length=2)),
                ('cohort_choices', models.CharField(choices=[('J', 'Jan Extended'), ('F', 'Feb Standard'), ('A', 'Aug Standard'), ('M', 'May Express'), ('O', 'October Express')], max_length=1)),
                ('class_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1)),
                ('firstname', models.CharField(max_length=130)),
                ('lastname', models.CharField(max_length=130)),
                ('preferred', models.CharField(blank=True, max_length=130, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentlist',
            options={'get_latest_by': 'uploaded_at'},
        ),
    ]
