# Generated by Django 2.2 on 2019-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190406_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scaffold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_choices', models.CharField(choices=[('18', '2018'), ('19', '2019'), ('20', '2020'), ('21', '2021')], max_length=2)),
                ('cohort_choices', models.CharField(choices=[('J', 'Jan Extended'), ('F', 'Feb Standard'), ('A', 'Aug Standard'), ('M', 'May Express'), ('O', 'October Express')], max_length=1)),
                ('docx', models.FileField(upload_to='scaffold/%Y-%m-%d/%H/%M', verbose_name='Scaffold')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'uploaded_at',
            },
        ),
    ]
