# Generated by Django 2.2 on 2019-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_scaffold_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='sl_xls',
            field=models.FileField(upload_to='student_list/%Y-%m-%d/%H/%M', verbose_name='Student List'),
        ),
    ]
