# Generated by Django 2.2 on 2019-04-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190408_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scaffold',
            old_name='docx',
            new_name='pdf',
        ),
    ]
